### ISSUE TITLE
"More Options" on the unlock screen doesn't take me anywhere

### ISSUE THREAD

**Issue by paulyoung** [Psychedelic/plug-mobile#254]
I see an animation when I tap on the text but nothing happens.

**Comment by paulyoung** [comment]
Still an issue for me on v0.1.0(67)

**Comment by ignaciosantise** [comment]
Hi @paulyoung! can you test this in the production app? The current version in the App Store is 0.1.1 (8)

You can follow us in [Twitter]( https://twitter.com/plug_wallet ) to see new updates or join our [Discord](https://discord.gg/yVEcEzmrgm) 🎉
