### ISSUE TITLE
Import Custom Tokens

### ISSUE THREAD

**Issue by riveign** [Psychedelic/plug-mobile#393]
# Description

**Task:** Implement `Custom Token` flow

### Scope:

- Custom token will be implemented **only** for tokens not for NFTs

## Acceptance Criteria

- Implement Design & Functionality of Custom Token iOS/Android
    - Figma Ticket: [Here](https://www.figma.com/file/no61f8MMPQlPUIaXSX3zCn/Plug---Wallet?node-id=8406%3A2489)

### Create Flow:

- DAB learn more button should take the user to [here](https://dab-ooo.typeform.com/token-list)
    - For now, the user will be taken the default browser on the phone (later to be discuss if we will be taking the user to an app-browser)
- When the search criteria has **no search result**, the text `Add Custom Token` when the user taps on it, the user will be taken to this screen

- If the `Token canister ID` introduced is incomplete, incorrect, or does not exist, the following needs to occur:
    - The continue button should remain disabled
    - incorrect &/or doesn’t exist → `Invalid token canister id` message below the Token interface Standard field, imititating what we do with the contacts when already exists
    - incomplete → leave the Continue button just disabled, no error message here

- Once the token is added, it should be visible only for that account, not for the rest of the subaccounts
- Custom tokens can be transferred
    - Transfer flow for custom tokens should be as usual for the rest of the tokens and following the partner in the exte
- If a custom token has been already added in the wallet, allow the user the flow but don’t show the custom token duplicated
- If the custom token balance ran out, it should remain visible in the screen
- When typing in the search bar of the custom token, results should appear based on matching criteria
- Back & Close button should behaves as it does for the rest of the screen
- APP-add assets screen will display all the DAB tokens
- If the user add the token and has no balance, the token should be added as expected

**Comment by ignaciosantise** [comment]
Comments for QA:
* The text input component was refactored, so we should check screens that use it: Login, Create/Import account flow, send money, add/edit contact, biometric settings
