### ISSUE TITLE
[Wallet Connect] Sonic won't connect with plug

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#415]
## Testing Information

- **OS:** Android
- **Cellphone** **version:** Samsung Galaxy Note 9
- **Version Plug mobile:** v0.2.0(6)

## Precondition

- You must to try connect Sonic with Plug

**Issue:** When trying to connect Sonic with Plug mobile the application starts loading and never ends

- **Steps to recreate**
    - Enter sonic
    - Press the Connect button
    - Allow Sonic to bond with Plug
 
**Current:** The app starts loading and never finishes, so it never connects
 
https://user-images.githubusercontent.com/108067829/188704505-fae69987-5a10-4b85-bf0a-f6313b5d28ba.mp4

**Expected:** Sonic should connect with Plug

**Comment by kevin4476** [comment]
## Testing Information

- **OS:** Android
- **Cellphone** **version:** Samsung Galaxy Note 9
- **Version Plug mobile:** v0.2.0(6)

## Precondition

- You must to try connect Sonic with Plug

**Issue:** When trying to connect Sonic with Plug mobile the application starts loading and never ends

- **Steps to recreate**
    - Enter sonic
    - Press the Connect button
    - Allow Sonic to bond with Plug
 
**Current:** The app starts loading and never finishes, so it never connects
 
https://user-images.githubusercontent.com/108067829/188704505-fae69987-5a10-4b85-bf0a-f6313b5d28ba.mp4

**Expected:** Sonic should connect with Plug

## 🌳 QA Testing Notes

**Comment by mattgle** [comment]
Solved in: https://github.com/Psychedelic/plug-mobile/pull/450

**Comment by karlamiesesfleek** [comment]
### QA Notes

> QA Status: This has been re-tested on Kevin's cellphone with this [version](https://discord.com/channels/837010835423494144/1009070838110240799/1021479561751445595), and the issue is no longer occuring.
