### ISSUE TITLE
[Android] The application puts letters in uppercase

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#416]
**Testing Information**
**OS:** Android
**Cellphone version:** Samsung Galaxy Note 9
**Version Plug mobile:** v0.2.0(6)
**Precondition**
- You must to try write in any box of the app
**Issue:** The app capitalizes the first letter without warning
to user

**Steps to recreate**
- Press Import Wallet
- Enter password
- Press Continue button
- Type Recovery Phrase
**Current:** When you go to type the recovery phrase, the app capitalizes the first letter

https://user-images.githubusercontent.com/108067829/189791382-f90b833f-dfc8-4da8-9735-1d348ffb9714.mp4

**Expected:** The app shouldn't capitalizes the first letter without to notify the user that is writing in capital letters

🌳 **Additional Notes**
✅ This occurs in the following situations:** When you are going to place the Recovery phrase

**Comment by kevin4476** [comment]
## Testing Information

- **OS:** Android
- **Cellphone** **version:** Samsung Galaxy Note 9
- **Version Plug mobile:** v0.2.0(6)

## Precondition

- You must to try write in any box of the app

**Issue:** The app capitalizes the first letter without warning
to user

- **Steps to recreate**
    - Press Import Wallet
    - Enter password
    - Press Continue button
    - Type Recovery Phrase
- **Current:** When you go to type the recovery phrase, the app capitalizes the first letter
    
    [[WhatsApp Video 2022-09-06 at 9.30.33 AM.mp4](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/291810ee-5357-44ba-8676-c86fb6abc32f/WhatsApp_Video_2022-09-06_at_9.30.33_AM.mp4)](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/291810ee-5357-44ba-8676-c86fb6abc32f/WhatsApp_Video_2022-09-06_at_9.30.33_AM.mp4)
    

- **Expected:** The app shouldn't capitalizes the first letter without to notify the user that is writing in capital letters

---

## 🌳 QA Testing Notes

<aside>
✅ **This occurs in the following situations:**
1. When you are going to place the Recovery phrase

</aside>

**Comment by ignaciosantise** [comment]
@kevin4476 is this still happening in the last version?

**Comment by karlamiesesfleek** [comment]
### QA Testing Notes
✅ Passes testing

Cc: @ignaciosantise I have no perms to close tickets, can you close it for me please?
