### ISSUE TITLE
[Wallet Connect] Error in token prices

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#417]
## Testing Information

- **OS:** Android
- **Cellphone** **version:** Samsung Galaxy Note 9 
- **Version Plug mobile:** v0.2.0(6)

## Precondition
Have Plug Mobile version 0.2.0(6) 
---

**Issue:** The application incorrectly displays the price of the tokens

- **Steps to recreate**
    - Launch app
    - Add to token screen a token without balance
- **Current:** Under of the token name the app shows "0" 

![Image](https://user-images.githubusercontent.com/108067829/188724928-4b540f7a-145d-4876-a790-8fcee11ff3c8.jpeg)

- **Expected:** The app should shows the token price of the token without balance of the following form

![Image](https://user-images.githubusercontent.com/108067829/188725583-8aeaba04-d7f1-40a7-9972-b31359dd89a0.jpg)

**Comment by mattgle** [comment]
Closing this issue since is fixed in newer versions of the app
