### ISSUE TITLE
[Android] Application does not copy the recovery phrase

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#423]
**Testing Information**
**OS:** Android
**Cellphone version:**Samsung Galaxy Note 9
**Version Plug mobile:**v0.2.0(9)
**Precondition**
- Try to get the recovery phrase
- Issue: When trying to copy the recovery phrase the application does not add it to the clipboard

**Steps to recreate**
- Launch app
- Go to profile tab
- Go to settings
- Press Seed Phrase button
- Enter the password
- Press Reveal Seed Phrase button
- Press Copy to clipboard button
**Current:** The application does not copy the recovery phrase

https://user-images.githubusercontent.com/108067829/189790400-cc983030-7b4e-4e47-a976-f0159eb1e22b.mp4

**Expected:** The recovery phrase should copy to the clipboard

**Comment by kevin4476** [comment]
## Testing Information

- **OS:** Android 
- **Cellphone** **version:** Samsung Galaxy Note 9 
- **Version Plug mobile:** v0.2.0(6)

## Precondition

- Be inside the app

---

**Issue:**  When trying to copy the recovery phrase the application does not add it to the clipboard

- **Steps to recreate**
    - Launch app
    - Go to profile tab
    - Go to settings
    - Press Seed Phrase button
    - Enter the password
    - Press Reveal Seed Phrase button
    - Press Copy to clipboard button
- **Current:** The application does not copy the recovery phrase to the clipboard

https://user-images.githubusercontent.com/108067829/189194665-945fbc7d-8850-4087-96d7-8550ba91f8e1.mp4

- **Expected:** The should copy the recovery phrase to the clipboard

---

## 🌳 QA Testing Notes

<aside>
✅

</aside>

**Comment by ignaciosantise** [comment]
https://github.com/Psychedelic/plug-mobile/pull/424

**Comment by karlamiesesfleek** [comment]
### QA Testing Notes
✅ Passes testing
