### ISSUE TITLE
[Android] Wrong user interface

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#426]
**Testing Information**
**OS:** Android
**Cellphone version:** Samsung Galaxy Note 9
**Version Plug mobile:** 0.2.0(9)
**Precondition**
Have cellphone in dark mode
**Issue:** When trying to delete a token, the app incorrectly displays the delete message

**Steps to recreate**
- Launch app
- Press a token
- Press Delete button
**Current:** The application shows a popup with the confirmation message to delete a token, but the design of this is wrong
Image
![189307641-0934049e-82eb-4b20-845b-398452abb638](https://user-images.githubusercontent.com/108067829/189791145-27321e00-2cfa-4a34-8062-141f4e08aac3.jpeg)
**Expected:** The message should look like this
![189307952-c7125de5-3c93-4d36-b091-2f5a7d6f9e56](https://user-images.githubusercontent.com/108067829/189791185-17b46a6b-b843-46ad-a901-4c7605abe9a5.jpeg)

**Comment by kevin4476** [comment]
## Testing Information

- **OS:** Android 
- **Cellphone** **version:** Samsung Galaxy Note 9 
- **Version Plug mobile:** 0.2.0(9)

## Precondition

- Have cellphone in dark mode

---

**Issue:**  When trying to delete a token, the app incorrectly displays the delete message

- **Steps to recreate**
    - Launch app
    - Press a token
    - Press Delete button
- **Current:** The application shows a popup with the confirmation message to delete a token, but the design of this is wrong


![Image](https://user-images.githubusercontent.com/108067829/189307641-0934049e-82eb-4b20-845b-398452abb638.jpeg)



- **Expected:** The message should look like this


![Image](https://user-images.githubusercontent.com/108067829/189307952-c7125de5-3c93-4d36-b091-2f5a7d6f9e56.jpeg)


---

## 🌳 QA Testing Notes

<aside>
✅

</aside>

**Comment by karlamiesesfleek** [comment]
### QA Testing Notes
✅ Passes testing

![image](https://user-images.githubusercontent.com/94389748/189792172-a01caca7-448d-46fa-8481-880d81e49fb2.png)


Cc: @ignaciosantise I have no perms to close tickets, can you close it for me please?
