### ISSUE TITLE
[WalletConnect] Overlapping

### ISSUE THREAD

**Issue by karlamiesesfleek** [Psychedelic/plug-mobile#428]
### Issue:

When there's a drawer open, like the settings screen, and then the WC request connection appear, the settings screen doesn't close to show the WC request screen, instead the user needs to close the Settings screen and continue with the flow. 

## Precondition
- Have [this](https://discord.com/channels/837010835423494144/1009070838110240799/1015047800674865274) Plug's version downloaded 
- Make sure to have the Settings screen opened before connecting to Sonic

## Testing Information
- Chrome 
- Galaxy Note 9

## Steps to recreate

- Launch [Sonic](https://2aoj2-aaaaa-aaaad-qa4qq-cai.ic.fleek.co/) in your Chrome's browser
- Tap on Connect

**Current behavior**
The user is sent to Plug Mobile to the setting screen

**Expected behavior**
The setting screen should close or be overlapped by the WC request connection screen

**Comment by mattgle** [comment]
TODO: Close all opened modals when the IntialConnection has begin.

**Comment by mattgle** [comment]
https://github.com/Psychedelic/plug-mobile/pull/449

**Comment by karlamiesesfleek** [comment]
### QA Testing Notes

> Passes testing ✔️
