### ISSUE TITLE
[ICNS-part 2] Add error message for nonexistent ICNS

### ISSUE THREAD

**Issue by alinasytnik** [Psychedelic/plug-mobile#430]
## Description
Add the error message for nonexistent ICNS names for ICNS input on the Add contact screen.

## Steps to Reproduce
1. Login into Plug
2. Go to the Profile tab
3. Click on the Settings icon-button
4. Go to the Contacts
5. Click on Add Contact button
6. Fill name input
7. Fill in the icns name input with a icns that does not exist
- Current: The user doesn't get any errors, when putting nonexistent icns, only Add Contact button becomes disabled.

## Expected behavior
The "Nonexistent ICNS name" error should be shown.

## Screen shots
https://user-images.githubusercontent.com/33018206/189661269-361d5455-cada-4ee2-b116-30cf76288619.mp4

## Smartphone (please complete the following information):
 - Device: iPhone 11
 - OS: iOS 15.6.1
 - Version: 0.2.0(14)

**Comment by mattgle** [comment]
Fixed in https://github.com/Psychedelic/plug-mobile/pull/433
