### ISSUE TITLE
[ICNS] App puts the first letter in capital letter

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#434]
## Testing Information

- **OS:** Android & iOS 
- **Cellphone** **version:** Samsung Galaxy Note 9 & Iphone XS
- **Version Plug mobile:** Android version: 0.2.0(9) & iOS version: 0.2.0(14)

## Precondition

- Have an ICNS

**Issue:** When trying to add a contact the app put the first letter in capital letters, so the app cannot agregar the contact

- **Steps to recreate**
    - Launch app
    - Go to Profile tab
    - Press Setting button
    - Press Contacts button
    - Press Add contact button
    - Type any name
    - Type a validate ICNS
- **Current:** How the app put the first letter in capital letter i cannot to add the contact

https://user-images.githubusercontent.com/108067829/189782169-b8a1186b-e0cc-4f05-8693-e35cbef5b9b0.mp4

- **Expected:** The app shouldn't put any letter in capital letter

**Comment by kevin4476** [comment]
## Testing Information

- **OS:** Android & iOS 
- **Cellphone** **version:** Samsung Galaxy Note 9 & Iphone XS
- **Version Plug mobile:** Android version: 0.2.0(9) & iOS version: 0.2.0(14)

## Precondition

- Have an ICNS

---

**Issue:** When trying to add a contact the app put the first letter in capital letters, so the app cannot agregar the contact

- **Steps to recreate**
    - Launch app
    - Go to Profile tab
    - Press Setting button
    - Press Contacts button
    - Press Add contact button
    - Type any name
    - Type a validate ICNS
- **Current:** How the app put the first letter in capital letter i cannot to add the contact


https://user-images.githubusercontent.com/108067829/189782169-b8a1186b-e0cc-4f05-8693-e35cbef5b9b0.mp4



- **Expected:** The app shouldn't put any letter in capital letter
 
---

## 🌳 QA Testing Notes

<aside>
✅

</aside>

**Comment by mattgle** [comment]
Fixed in https://github.com/Psychedelic/plug-mobile/pull/433
