### ISSUE TITLE
[ICNS] Profile tab doesn't shows the ICNS

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#435]
**Testing Information**
--
**OS:** Android & iOS
**Cellphone version:** Samsung Galaxy Note 9 & Iphone XS
**Version Plug mobile:** Android version: 0.2.0(9) & iOS version: 0.2.0(14)

**Precondition**
--
- Have a ICNS

**Issue:** The application shows as issuer an ICNS when sending a token, but not when sending NFTs
**Steps to recreate**
- Launch app
- Send a token
- Send a NFT
- Review these transactions in the account you sent the token and NFT to

**Current:** The token transaction say "From X.icp " but the NFT transaction say "From (ID)"
![189784431-8bf32d26-b267-4085-a095-1a741d9709fb](https://user-images.githubusercontent.com/108067829/189794589-133f02cc-e7fb-44d0-b1a5-7737fec336bb.jpeg)

**Expected:** The app should display the ICNS no matter what is being sent

**Comment by kevin4476** [comment]
## Testing Information

- **OS:** Android & iOS
- **Cellphone** **version:** Samsung Galaxy Note 9 & Iphone XS
- **Version Plug mobile:** Android version: 0.2.0(9) & iOS version: 0.2.0(14)

## Precondition

- Have a ICNS

---

**Issue:** The application shows as issuer an ICNS when sending a token, but not when sending NFTs

- **Steps to recreate**
    - Launch app
    - Send a token
    - Send a NFT
    - Review theses transactions in another device
- **Current:** The token transaction say "From X.icp " but the NFT transaction say "From (ID)"


![Image](https://user-images.githubusercontent.com/108067829/189784431-8bf32d26-b267-4085-a095-1a741d9709fb.jpeg)



- **Expected:** The app should display the ICNS no matter what is being sent
 

---

## 🌳 QA Testing Notes

<aside>
✅

</aside>

**Comment by mattgle** [comment]
This is fixed by @tomiir in plug-controller
