### ISSUE TITLE
[Plug-Mobile] Wallet not unlocking

### ISSUE THREAD

**Issue by karlamiesesfleek** [Psychedelic/plug-mobile#436]
### Issue
When you are loggged into your wallet that has `Biometrics` turned on, then you log out, create a wallet without biometrics, and before tapping on `I've saved these words` button, you close the app, and relaunch it, the app won't unlock because the login screen seems to be sync with the previous wallet's credentials. 

**Precondition:**
- User should be logged into the wallet
- Wallet must have biometrics turned on
- Password for that wallet should be different to the one we are going to use in the `Steps` segment below

**Test Information**
- OS: Android/iOS

**Steps:**
- Log out from you Plug Wallet account
- Tap on the `Create Account` button
- Introduce a password and leave biometrics turned off
- Tap on `Next`
- DO NOT tap on `I've saved these words` button
- Close the app
- Relaunch the app
- Trigger biometrics

**Current behavior**
Account won't unblocked

https://user-images.githubusercontent.com/94389748/189795905-d21a39a1-e705-48a6-941f-439a98393ef6.mp4

**Expected behavior**
Login screen should refresh and process the information pointing to the new account created. Actually in the BE I think it does it, but in the front it seems to be picking the old wallet's credentials.

**Comment by ignaciosantise** [comment]
Duplicated https://github.com/Psychedelic/plug-mobile/issues/452
