### ISSUE TITLE
[ICNS] App doesn't allows to add contacts with PID

### ISSUE THREAD

**Issue by kevin4476** [Psychedelic/plug-mobile#438]
## Testing Information

- **OS:** Android & iOS
- **Cellphone** **version:** Samsung Galaxy Note 9 & Iphone XS
- **Version Plug mobile:** Android version: 0.2.0(9) & iOS version: 0.2.0(14)

## Precondition

- Have an ICNS

---

**Issue:**  The app doesn't allow to add contacts with the principal ID

- **Steps to recreate**
    - Launch app
    - Go to Profile tab
    - Press Settings button
    - Press Contacts button
    - Press Add contact button
    - Type a name
    - Paste a Principal ID 
    - Press Add Contact button
   
- **Current:** The application does not add the contact
  

https://user-images.githubusercontent.com/108067829/189930551-187c28b6-063c-47c0-b91d-9ce7abf8216d.mp4

- **Expected:** The app should allow to add contacts with ICNS names and Principals ID

**Comment by mattgle** [comment]
Fixed in https://github.com/Psychedelic/plug-mobile/pull/433
