### ISSUE TITLE
[WalletConnect] Connection Request & no logged account

### ISSUE THREAD

**Issue by karlamiesesfleek** [Psychedelic/plug-mobile#443]
### Issue
Login view appears in Plug Mobile when a request is made and any account is logged in. 

**Test Information**
- Phone: Galaxy Note 8
- Browser: Chrome
- Test's version: https://discord.com/channels/837010835423494144/1009070838110240799/1015047800674865274
- Sonic's version https://2aoj2-aaaaa-aaaad-qa4qq-cai.ic.fleek.co/swap

**Precondition**
- You should NOT be logged into any wallet

**Steps to Recreate**
- Launch [Sonic](https://2aoj2-aaaaa-aaaad-qa4qq-cai.ic.fleek.co/swap) in chrome
- Tap on Connect
**Current behavior**
The user is taken to the login screen

https://user-images.githubusercontent.com/94389748/190430790-b4671f5d-d493-4fcf-96c6-08b17171fab1.mp4

**Expected behavior**
There should be a message indicating the user to create a wallet or import one. 

**Additional Notes**
Rainbow send the user to a screen with create wallet and/or import.

**Comment by mattgle** [comment]
Solved in: https://github.com/Psychedelic/plug-mobile/pull/450

**Comment by karlamiesesfleek** [comment]
### QA Testing Notes

> Passes testing
