### ISSUE TITLE
[WalletConnect] Transactions & Infinitive Load

### ISSUE THREAD

**Issue by karlamiesesfleek** [Psychedelic/plug-mobile#444]
## Issue
All transactions produce an infinitive load in Sonic upon Approval request. 

**Transactions**
- Swap
- Withdraw
- Deposit
- Create Liquidity

**Test Information**
- Phone: Galaxy Note 8
- Browser: Chrome
- Test's version: https://discord.com/channels/837010835423494144/1009070838110240799/1015047800674865274
- Sonic's version https://2aoj2-aaaaa-aaaad-qa4qq-cai.ic.fleek.co/swap

**Precondition**
- Sonic and WC should be linked

**Steps to Recreate**
- Launch [Sonic](https://2aoj2-aaaaa-aaaad-qa4qq-cai.ic.fleek.co/swap) in chrome
- Go to the assets tab
- Start a deposit or withdraw

**Current behavior**
App get stuck loading

![Image](https://user-images.githubusercontent.com/94389748/190433189-23e4d83d-76c3-477d-a697-cdb94254be4b.png)

**Expected behavior**
Transaction should be succesful. 

**Additional information**
No errors in the console not in the Network/Console tabs
![image](https://user-images.githubusercontent.com/94389748/192310257-c1db2cff-29cd-4079-9ca0-bdea43b03c81.png) 
![image](https://user-images.githubusercontent.com/94389748/192310481-d75bb684-ee21-45f4-b627-715f9a6191eb.png)

**Comment by ignaciosantise** [comment]
@karlamiesesfleek is this still happening?

**Comment by karlamiesesfleek** [comment]
Ops! Sorry, no longer. This is fixed.
