### ISSUE TITLE
Review memory problems triggered by big images

### ISSUE THREAD

**Issue by ignaciosantise** [Psychedelic/plug-mobile#470]
## Description
* Changed the way we handle assets, transactions and NFTs to improve memory usage

This change solves https://github.com/Psychedelic/plug-mobile/issues/445 too

## Comments for QA
* The flows affected by changes are:
 * Send flow
 * Add custom token
 * Remove custom token
 * Transfer NFT

**Comment by alinasytnik** [comment]
### Issue

**After sending ICP, it takes about 5 minutes to update the balance of ICP on the Tokens tab** 

Device: iPhone 14
OS: iOS 16.0.1
Plug version: 0.3.0(3)

Additional Information: Afaik, one of our users had the same problem in the extension.
